// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aovwphpajzbzpsefjcrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvdndwaHBhanpienBzZWZqY3JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MjE3MzYsImV4cCI6MjA3Mzk5NzczNn0.BfxXz7qmDQHJUUQOca-BSLgaXzLXwkbazyxWZWABDTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});